### ISSUE TITLE
Sending data over uart from within two threads mixes data up

### ISSUE THREAD

**Issue by bromagosa** [whitecatboard/LuaOS#13]
This code:

```
a = function() while true do uart.write(uart.UART1, '1234567890\r\n') end end
b = function() while true do uart.write(uart.UART1, 'qwertyuiop\r\n') end end
thread.start(a); thread.start(b)
```

Shows:

```
12345678qwertyuiop
90
1234567qwertyuiop
890
qwerty1234567890
uiop
12345qwertyuiop
67890
1234qwertyuiop
567890
567890ertyuiop
1234
    qwertyuiop567890
1234
qwertyuio567890
1234p
qwertyuio567890
123p
qwertyuio4567890
12p
qwertyuio34567890
```

The ```uart.write``` function should ideally be atomic.

**Comment by jolivepetrus** [comment]
You are right!!

We have take the following actions related to this issue:

UART functions are not thread-safe, except for the write function to the console (uart.CONSOLE), and should be only called from one thread. This is due to the following design decisions:

* More that one thread may need to write something to the console. In this case thread-safe is needed.
* Read/Write to/from an UART device (for example a GPS) must be controlled only one thread. In this case thread-safe is not needed.

Now write to the console are thread-safe.

We also added uart.CONSOLE constant to identify the console easily.
